#!/bin/bash
# ==============================================================================
# aaPanel Deployment Script
# ==============================================================================

set -e

echo "🚀 GXQ Studio - aaPanel Deployment"
echo "===================================="

echo ""
echo "aaPanel Setup Instructions:"
echo "============================"
echo ""
echo "Prerequisites:"
echo "- aaPanel installed (https://www.aapanel.com/)"
echo "- Docker and Docker Compose installed via aaPanel"
echo "- Domain configured (optional but recommended)"
echo ""
echo "Setup Steps:"
echo ""
echo "1. Install Docker via aaPanel:"
echo "   - Go to App Store"
echo "   - Search for 'Docker'"
echo "   - Install Docker and Docker Compose"
echo ""
echo "2. Create Website in aaPanel:"
echo "   - Website > Add Site"
echo "   - Domain: your-domain.com (or use IP)"
echo "   - Create FTP: No"
echo "   - Create Database: Optional"
echo "   - PHP Version: Pure Static"
echo ""
echo "3. Upload Files:"
echo "   - Use File Manager or FTP"
echo "   - Upload all files to /www/wwwroot/your-domain.com/"
echo "   - Or clone via Terminal: git clone https://github.com/SMSDAO/reimagined-jupiter.git"
echo ""
echo "4. Configure Environment:"
echo "   - Copy .env.example to .env"
echo "   - Edit .env with your settings"
echo "   - Set proper file permissions (755 for directories, 644 for files)"
echo ""
echo "5. Install Node.js via aaPanel:"
echo "   - App Store > Node.js Project Manager"
echo "   - Install Node.js v20"
echo ""
echo "6. Deploy with Docker Compose:"
echo "   - Open Terminal in aaPanel"
echo "   - cd /www/wwwroot/your-domain.com"
echo "   - docker-compose up -d"
echo ""
echo "7. Configure Reverse Proxy:"
echo "   - Website > your-domain.com > Reverse Proxy"
echo "   - Target URL: http://127.0.0.1:3001 (webapp)"
echo "   - Enable cache: No"
echo "   - Add custom locations:"
echo "     * /api -> http://127.0.0.1:3000"
echo ""
echo "8. SSL Certificate (Recommended):"
echo "   - Website > your-domain.com > SSL"
echo "   - Let's Encrypt > Apply"
echo "   - Force HTTPS: Enable"
echo ""
echo "9. Firewall Rules:"
echo "   - Security > Firewall"
echo "   - Add rules for ports 3000, 3001"
echo "   - Or use reverse proxy and only expose 80/443"
echo ""
echo "10. Process Management:"
echo "    - Use Docker Compose to manage services"
echo "    - Or use PM2 via aaPanel Node.js Manager"
echo ""
echo "Management Commands:"
echo "===================="
echo ""
echo "Start services:"
echo "  cd /www/wwwroot/your-domain.com && docker-compose up -d"
echo ""
echo "Stop services:"
echo "  cd /www/wwwroot/your-domain.com && docker-compose down"
echo ""
echo "View logs:"
echo "  cd /www/wwwroot/your-domain.com && docker-compose logs -f"
echo ""
echo "Update application:"
echo "  cd /www/wwwroot/your-domain.com"
echo "  git pull"
echo "  docker-compose down"
echo "  docker-compose build"
echo "  docker-compose up -d"
echo ""
echo "✅ Setup guide complete"
